blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = "blog"
urlpatterns = [
   path("" , blog_view , name="index"),
   path("<int:pid>" , blog_single , name="single"),
   path("category/<str:cat_name>" , blog_view , name = "category"),
   path("tag/<str:tag_name>" , blog_view , name = "tag"),
   path("author/<str:author_username>" , blog_view , name = "author"),
   path("search/" , blog_search , name = "search"),
    path("rss/feed/", LatestEntriesFeed()),
   # path("test" , test , name = "test"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar

sitemaps = {
    "static": StaticViewSitemap,
    "blog" : BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('url address' , 'view')
    path("" , include("website.urls")),
    path("blog/" , include("blog.urls")),
    path("accounts/" , include("accounts.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("sitemap.xml" , sitemap , {"sitemaps" : sitemaps} ,
        name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt" , include("robots.urls")),
    path("__debug__/" , include(debug_toolbar.urls)),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 255)
    def __str__(self):
        return self.name
class Post(models.Model):

    image = models.ImageField(upload_to = "blog/" , default = "blog/default.jpg.jpg")
    author = models.ForeignKey(User , on_delete = models.SET_NULL , null = True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_date"]
    def __str__(self):
        # return "{} - {}".format( self.title , self.id)
        return self.title
    def snippets(self):
        return self.content[: 100] + "..."
    def get_absolute_url(self):
        return reverse("blog:single" , kwargs = {"pid" : self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post , on_delete = models.CASCADE)
    name = models.CharField(max_length = 255)
    email = models.EmailField()
    subject = models.CharField(max_length = 255)
    message = models.TextField()
    approved = models.BooleanField(default = False)
    created_date = models.DateTimeField(auto_now_add = True)
    updated_date = models.DateTimeField(auto_now = True)
    class Meta:
        ordering = ["-created_date"]
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField

class CommenttForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["post" , "name" , "email" , "subject" , "message"]

blog/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from blog.models import Post , Comment
from django.core.paginator import Paginator , EmptyPage , PageNotAnInteger
from blog.forms import CommenttForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.
# @login_required
def blog_view(request , **kwargs):
    posts = Post.objects.filter(status = 1)
    if kwargs.get("cat_name") != None:
        posts = posts.filter(category__name = kwargs["cat_name"])
    if kwargs.get("author_username") != None:
        posts = posts.filter(author__username = kwargs["author_username"])
    if kwargs.get("tag_name") != None:
        posts = posts.filter(tags__name__in = [kwargs["tag_name"]])
    posts = Paginator(posts , 3)
    try:
        page_number = request.GET.get("page")
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {"posts" : posts}
    return render(request , 'blog/blog-home.html' , context)
# @login_required(login_url="accounts:login")
# def blog_single(request , pid):
#     if request.method == "POST":
#         form = CommenttForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.add_message(request , messages.SUCCESS , "your comment submited successfully")
#         else:
#             messages.add_message(request , messages.ERROR , "your comment did not submited")      
#     posts = Post.objects.filter(status = 1)
#     post = get_object_or_404(posts , pk = pid)
#     if not post.login_require:
#         comments = Comment.objects.filter(post=post.id , approved = True)
#         form = CommenttForm()
#         context = {"post" : post , "comments" : comments , "form" : form}
#         return render(request , 'blog/blog-single.html' , context)
#     else:
#         return HttpResponseRedirect(reverse("accounts:login"))
def blog_single(request , pid):
    posts = Post.objects.filter(status=1)
    post = get_object_or_404(posts, pk=pid)
    if post.login_require:
        if not request.user.is_authenticated:
            from django.utils.http import urlencode
            from django.shortcuts import redirect, reverse
            login_url = reverse("accounts:login")
            params = urlencode({"next": request.path})
            return redirect(f"{login_url}?{params}")
    if request.method == "POST":
        form = CommenttForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your comment submitted successfully")
        else:
            messages.error(request, "Your comment did not submit")

    comments = Comment.objects.filter(post=post.id, approved=True)
    form = CommenttForm()
    context = {"post": post, "comments": comments, "form": form}
    return render(request, 'blog/blog-single.html', context)

# @login_required(login_url="accounts:login")
# def blog_single(request , pid):
#     posts = Post.objects.filter(status=1)
#     post = get_object_or_404(posts, pk=pid)

#     if request.method == "POST":
#         form = CommenttForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, "Your comment submitted successfully")
#         else:
#             messages.error(request, "Your comment did not submit")

#     comments = Comment.objects.filter(post=post.id, approved=True)
#     form = CommenttForm()
#     context = {"post": post, "comments": comments, "form": form}
#     return render(request, 'blog/blog-single.html', context)


def test(request):
    return render(request , "test.html")
def blog_category(request , cat_name):
    posts = Post.objects.filter(status = 1)
    posts = posts.filter(category__name = cat_name)
    context = {"posts" : posts}
    return render(request , "blog/blog-home.html" , context)
def blog_search(request):
    posts = Post.objects.filter(status = 1)
    if request.method == "GET":
        if s := request.GET.get("s"):
            posts = posts.filter(content__contains = s)
    context = {"posts" : posts}
    return render(request , "blog/blog-home.html" , context)

templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg'%}" alt=""></a>
</div>

templates/blog/blog-newsletter.html
<div class="single-sidebar-widget newsletter-widget">
    <h4 class="newsletter-title">Newsletter</h4>
    <p>
        Here, I focus on a range of items and features that we use in life without
        giving them a second thought.
    </p>
    <div class="form-group d-flex flex-row">
        <div class="col-autos">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
                    </div>
                </div>
                <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'">
            </div>
        </div>
        <a href="#" class="bbtns">Subcribe</a>
    </div>
    <p class="text-bottom">
        You can unsubscribe at any time
    </p>
</div>

templates/blog/blog-popular-posts.html
{% load humanize %}
{% load static %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Popular Posts</h4>
    <div class="popular-post-list">
        {% for post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{post.image.url}}" alt="">
            </div>
            <div class="details">
                <a href="{% url 'blog:single' pid=post.id %}">
                    <h6>{{post.title}}</h6>
                </a>
                <p>{{post.published_date|naturaltime}}</p>
            </div>
        </div>
        {% endfor %}
       
    </div>
</div>

templates/blog/blog-post-categories.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for name , count in categories.items %}
        <li>
            <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
                <p>{{name}}</p>
                <p>{{count}}</p>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-search.html
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:search' %}" method="get">
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/blog-tags.html
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        {% for tag in post.tags.all %}
        <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png'%}" alt="">
    <a href="#">
        <h4>Mahdi Kamalzare</h4>
    </a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you
        should have to spend money on boot camp when you can get. Boot camps have itssuppor ters
        andits detractors.
    </p>
</div>